// frontend-angular/src/app/shared/confirm-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-confirm-modal',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div *ngIf="open" class="modal fade show d-block" tabindex="-1" role="dialog" aria-modal="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Confirm delete</h5>
            <button type="button" class="btn-close" (click)="cancel.emit()"></button>
          </div>
          <div class="modal-body">
            <p class="mb-0">{{ message }}</p>
          </div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" (click)="cancel.emit()">Cancel</button>
            <button class="btn btn-danger" type="button" (click)="confirm.emit()">Delete</button>
          </div>
        </div>
      </div>
    </div>
    <div *ngIf="open" class="modal-backdrop fade show"></div>
  `,
})
export class ConfirmModalComponent {
  @Input() open = false;
  @Input() message = 'Are you sure?';
  @Output() confirm = new EventEmitter<void>();
  @Output() cancel = new EventEmitter<void>();
}

// frontend-react/src/components/ConfirmModal.jsx
export default function ConfirmModal({ open, message, onCancel, onConfirm }) {
  if (!open) return null;

  return (
    <>
      <div className="modal fade show d-block" tabIndex="-1" role="dialog" aria-modal="true">
        <div className="modal-dialog modal-dialog-centered" role="document">
          <div className="modal-content">
            <div className="modal-header">
              <h5 className="modal-title">Confirm delete</h5>
              <button type="button" className="btn-close" onClick={onCancel}></button>
            </div>
            <div className="modal-body"><p className="mb-0">{message}</p></div>
            <div className="modal-footer">
              <button className="btn btn-secondary" type="button" onClick={onCancel}>Cancel</button>
              <button className="btn btn-danger" type="button" onClick={onConfirm}>Delete</button>
            </div>
          </div>
        </div>
      </div>
      <div className="modal-backdrop fade show"></div>
    </>
  );
}
